/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServantsRouteImport } from './routes/servants'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentsIndexRouteImport } from './routes/students.index'
import { Route as AttendanceIndexRouteImport } from './routes/attendance.index'
import { Route as StudentsNewRouteImport } from './routes/students.new'
import { Route as StudentsImportRouteImport } from './routes/students.import'
import { Route as StudentsIdRouteImport } from './routes/students.$id'
import { Route as AttendanceSessionIdRouteImport } from './routes/attendance.$sessionId'

const ServantsRoute = ServantsRouteImport.update({
  id: '/servants',
  path: '/servants',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIndexRoute = StudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceIndexRoute = AttendanceIndexRouteImport.update({
  id: '/attendance/',
  path: '/attendance/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsNewRoute = StudentsNewRouteImport.update({
  id: '/students/new',
  path: '/students/new',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsImportRoute = StudentsImportRouteImport.update({
  id: '/students/import',
  path: '/students/import',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIdRoute = StudentsIdRouteImport.update({
  id: '/students/$id',
  path: '/students/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceSessionIdRoute = AttendanceSessionIdRouteImport.update({
  id: '/attendance/$sessionId',
  path: '/attendance/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/servants': typeof ServantsRoute
  '/attendance/$sessionId': typeof AttendanceSessionIdRoute
  '/students/$id': typeof StudentsIdRoute
  '/students/import': typeof StudentsImportRoute
  '/students/new': typeof StudentsNewRoute
  '/attendance/': typeof AttendanceIndexRoute
  '/students/': typeof StudentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/servants': typeof ServantsRoute
  '/attendance/$sessionId': typeof AttendanceSessionIdRoute
  '/students/$id': typeof StudentsIdRoute
  '/students/import': typeof StudentsImportRoute
  '/students/new': typeof StudentsNewRoute
  '/attendance': typeof AttendanceIndexRoute
  '/students': typeof StudentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/servants': typeof ServantsRoute
  '/attendance/$sessionId': typeof AttendanceSessionIdRoute
  '/students/$id': typeof StudentsIdRoute
  '/students/import': typeof StudentsImportRoute
  '/students/new': typeof StudentsNewRoute
  '/attendance/': typeof AttendanceIndexRoute
  '/students/': typeof StudentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/servants'
    | '/attendance/$sessionId'
    | '/students/$id'
    | '/students/import'
    | '/students/new'
    | '/attendance/'
    | '/students/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/servants'
    | '/attendance/$sessionId'
    | '/students/$id'
    | '/students/import'
    | '/students/new'
    | '/attendance'
    | '/students'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/servants'
    | '/attendance/$sessionId'
    | '/students/$id'
    | '/students/import'
    | '/students/new'
    | '/attendance/'
    | '/students/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ServantsRoute: typeof ServantsRoute
  AttendanceSessionIdRoute: typeof AttendanceSessionIdRoute
  StudentsIdRoute: typeof StudentsIdRoute
  StudentsImportRoute: typeof StudentsImportRoute
  StudentsNewRoute: typeof StudentsNewRoute
  AttendanceIndexRoute: typeof AttendanceIndexRoute
  StudentsIndexRoute: typeof StudentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servants': {
      id: '/servants'
      path: '/servants'
      fullPath: '/servants'
      preLoaderRoute: typeof ServantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/': {
      id: '/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof StudentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance/': {
      id: '/attendance/'
      path: '/attendance'
      fullPath: '/attendance/'
      preLoaderRoute: typeof AttendanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/new': {
      id: '/students/new'
      path: '/students/new'
      fullPath: '/students/new'
      preLoaderRoute: typeof StudentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/import': {
      id: '/students/import'
      path: '/students/import'
      fullPath: '/students/import'
      preLoaderRoute: typeof StudentsImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$id': {
      id: '/students/$id'
      path: '/students/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof StudentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance/$sessionId': {
      id: '/attendance/$sessionId'
      path: '/attendance/$sessionId'
      fullPath: '/attendance/$sessionId'
      preLoaderRoute: typeof AttendanceSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ServantsRoute: ServantsRoute,
  AttendanceSessionIdRoute: AttendanceSessionIdRoute,
  StudentsIdRoute: StudentsIdRoute,
  StudentsImportRoute: StudentsImportRoute,
  StudentsNewRoute: StudentsNewRoute,
  AttendanceIndexRoute: AttendanceIndexRoute,
  StudentsIndexRoute: StudentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
